### PR TITLE
Assignment 1 Swapnali

### PR DESCRIPTION
**Pull request by SwapnaliTTechnocredits**

### CODE REVIEW

**Review by VrushaliPTechnocredits — CHANGES_REQUESTED** [review]
Code to maximize window is already present in init.ChromeDriver() method. Again in Confirmation_msg() method first line for maximizing window is added. you can remove this line from Confirmation_msg() method.

**Review by VrushaliPTechnocredits — CHANGES_REQUESTED** [review]
In Q6: Instead of writing all validations in one method, you can create a separate method for each validation and call these methods in place of logic written, which can improve code readability.

**Comment by RashmiHRTechnocredits** [comment]
Q6: For password verification,  you can write both isempty and length validation in one  if condition using or operator
Q2: When I pass values to FN, LN and company,  the string in which you are storing these values taking only comany name. FN and LN are taking as null.

**Review by SwapnaliTTechnocredits — COMMENTED** [review]
Hi Vrushali,
Review comments provided by you are updated.
Hi Rashmi,
Q1 is working fine at my end, its not taking null values.Rest comments are updated.

**Review by RashmiHRTechnocredits — APPROVED** [review]

**Review by VrushaliPTechnocredits — APPROVED** [review]

**Review by KrishnaKTechnocredits — APPROVED** [review]
Nicely written, keep it up.

**Pull request merged**
