### PR TITLE
Selenium 1st assignment all code

### PR DESCRIPTION
**Pull request by ShashankGarad09**

### CODE REVIEW

**Review by MonalibTechnocredits — COMMENTED** [review]
Code looks good

**Review by VrushaliPTechnocredits — CHANGES_REQUESTED** [review]
Hi Shashank,
`public static void main(String[] args) throws InterruptedException 
	{
		System.setProperty("webdriver.chrome.driver","C:\\Work Docs\\Java\\Class\\3rd Weekend\\Eclipse\\resources\\chromedriver_win32\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.get("http://www.automationbykrishna.com/#");
		driver.manage().window().maximize();`

When I have run this code in my system I got below exception:

Exception in thread "main" java.lang.IllegalStateException: The driver executable does not exist: C:\Work Docs\Java\Class\3rd Weekend\Eclipse\resources\chromedriver_win32\chromedriver.exe
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:132)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:156)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:346)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:91)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at seleniumPractise.vrushali.KrishnaAutoRegistrationBlank_Assignment1.main(KrishnaAutoRegistrationBlank_Assignment1.java:22)

**Suggestion:**
Instead of giving local path for browser exe, you can call  Init.initChromeDriver() in main method for browser path, exe and browser maximize code. So that your code will be run in any system without any exception.

**Review by VrushaliPTechnocredits — CHANGES_REQUESTED** [review]
Its good to find element By.id or By.name, but here in assignments try to locate elements By.xpath or By.cssSelector. For practice purpose use different x-path and cssSelector in prgrams.

`void alertDemoValidation(WebDriver driver) throws InterruptedException
	{
		driver.findElement(By.id("basicelements")).click();
		Thread.sleep(2000);
		driver.findElement(By.name("ufname")).sendKeys("Shashank");
		driver.findElement(By.name("ulname")).sendKeys("Garad");
		driver.findElement(By.name("cmpname")).sendKeys("ThoughtWorks");`

**Comment by ShashankGarad09** [comment]
> Hi Shashank,
> `public static void main(String[] args) throws InterruptedException { System.setProperty("webdriver.chrome.driver","C:\\Work Docs\\Java\\Class\\3rd Weekend\\Eclipse\\resources\\chromedriver_win32\\chromedriver.exe"); WebDriver driver = new ChromeDriver(); driver.get("http://www.automationbykrishna.com/#"); driver.manage().window().maximize();`
> 
> When I have run this code in my system I got below exception:
> 
> Exception in thread "main" java.lang.IllegalStateException: The driver executable does not exist: C:\Work Docs\Java\Class\3rd Weekend\Eclipse\resources\chromedriver_win32\chromedriver.exe
> at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
> at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:137)
> at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:132)
> at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
> at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:156)
> at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:346)
> at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:91)
> at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:123)
> at seleniumPractise.vrushali.KrishnaAutoRegistrationBlank_Assignment1.main(KrishnaAutoRegistrationBlank_Assignment1.java:22)
> 
> **Suggestion:**
> Instead of giving local path for browser exe, you can call Init.initChromeDriver() in main method for browser path, exe and browser maximize code. So that your code will be run in any system without any exception.

Correct Vrushali. Thank you! Changes done.

**Comment by ShashankGarad09** [comment]
> Its good to find element By.id or By.name, but here in assignments try to locate elements By.xpath or By.cssSelector. For practice purpose use different x-path and cssSelector in prgrams.
> 
> `void alertDemoValidation(WebDriver driver) throws InterruptedException { driver.findElement(By.id("basicelements")).click(); Thread.sleep(2000); driver.findElement(By.name("ufname")).sendKeys("Shashank"); driver.findElement(By.name("ulname")).sendKeys("Garad"); driver.findElement(By.name("cmpname")).sendKeys("ThoughtWorks");`

I have used xpath only where i could not use id/name. I am doing xpath practice separately on other applications. Thank you!

**Comment by ShashankGarad09** [comment]
> Code looks good

Thank you Monali!

**Comment by ShashankGarad09** [comment]
Changes done!

**Review by VrushaliPTechnocredits — APPROVED** [review]
The code looks good to me.
Use XPath and cssSelector for practice purpose.

**Review by KrishnaKTechnocredits — APPROVED** [review]
This assignment is written nicely Shashank, Keep it up.

**Pull request merged**
