### PR TITLE
Assignment1

### PR DESCRIPTION
**Pull request by SoumyaSTechnocredits**
Assignment1

### CODE REVIEW

**Review by SwapnaliTTechnocredits — COMMENTED** [review]
Hi Soumya,
Instead of using driver.close() in a method.Use it in main method like we are going to use in TestNG in After Method or After class.

**Comment by AtulGTechnocredits** [comment]
**AlertDemo.java**

1. use driver.close() in a method instead of if condition as it is always a good practice to close the driver which we have initialised

**AlertExample.java**

1. use driver.close() in a method instead of if condition as it is always a good practice to close the driver which we have initialised
2. Instead of creating alertText variable you can directly use the text in equals method. This would help in optimisation of code.

**JavaScriptConfirmation.java**

1. Instead of creating alertText,strAccept ,strReject , preDefinedStringAccept and preDefinedStringReject variables you can directly use the text in equals method. This would help in optimisation of code.

**JavaScriptPrompt.java**

1. Instead of creating alertText, preDefinedStringAccept, strAccept, preDefinedStringReject and strReject  variables you can directly use the text in equals method. This would help in optimisation of code

**LoginAlert.java**

1. Instead of creating alertBlank, alertPasswordBlank, alertPasswordShortlt8, alertPasswordShorteq8 and  alertPasswordShortgt8  variables you can directly use the text in equals method. This would help in optimisation of code

**RegistrationAlerts.java**

1. BlankFieldAlertValidation can be renamed as blankFieldAlertValidation as camel casing is best practice
2. Instead of creating alertFullname, alertAdress, alertEmail, alertWrongEmail, alertCity, alertOrganization, alertUsername, alertUsernameMismatch, alertPassword, alertReenterPasswordMatch and alertSubmit   variables you can directly use the text in equals method. This would help in optimisation of code 
3. use driver.close() in a method instead of if condition as it is always a good practice to close the driver which we have initialised

**Review by AtulGTechnocredits — CHANGES_REQUESTED** [review]
**AlertDemo.java**

1. use driver.close() in a method instead of if condition as it is always a good practice to close the driver which we have initialised

**AlertExample.java**

1. use driver.close() in a method instead of if condition as it is always a good practice to close the driver which we have initialised
2. Instead of creating alertText variable you can directly use the text in equals method. This would help in optimisation of code.

**JavaScriptConfirmation.java**

1. Instead of creating alertText,strAccept ,strReject , preDefinedStringAccept and preDefinedStringReject variables you can directly use the text in equals method. This would help in optimisation of code.

**JavaScriptPrompt.java**

1. Instead of creating alertText, preDefinedStringAccept, strAccept, preDefinedStringReject and strReject  variables you can directly use the text in equals method. This would help in optimisation of code

**LoginAlert.java**

1. Instead of creating alertBlank, alertPasswordBlank, alertPasswordShortlt8, alertPasswordShorteq8 and  alertPasswordShortgt8  variables you can directly use the text in equals method. This would help in optimisation of code

**RegistrationAlerts.java**

1. BlankFieldAlertValidation can be renamed as blankFieldAlertValidation as camel casing is best practice
2. Instead of creating alertFullname, alertAdress, alertEmail, alertWrongEmail, alertCity, alertOrganization, alertUsername, alertUsernameMismatch, alertPassword, alertReenterPasswordMatch and alertSubmit   variables you can directly use the text in equals method. This would help in optimisation of code 
3. use driver.close() in a method instead of if condition as it is always a good practice to close the driver which we have initialised

**Review by AtulGTechnocredits — APPROVED** [review]

**Review by SwapnaliTTechnocredits — APPROVED** [review]

**Review by KrishnaKTechnocredits — APPROVED** [review]
Good job, keep it up !!

**Pull request merged**
